In [3]:
import pandas as pd
df=pd.read_csv("/content/sample_data/student_performance.csv")
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [4]:
df

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print(df.shape)
print(df.head().shape)
print(df.tail().shape)

(30, 13)
(5, 13)
(5, 13)
30

In [ ]:
print("no of student:",df.shape[0])
print("no of columns:",df.shape[1])

no of student: 30
no of columns: 13

In [ ]:
print("columns in the dataset:",df.columns.tolist())

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
print(df.describe())

        student_id        age  semester  math_score  science_score  \
count    30.000000  30.000000      30.0   30.000000      30.000000
mean   1015.500000  19.733333       2.0   76.066667      77.833333
std       8.803408   0.739680       0.0   11.467896       8.554423
min    1001.000000  19.000000       2.0   56.000000      61.000000
25%    1008.250000  19.000000       2.0   67.250000      71.250000
50%    1015.500000  20.000000       2.0   75.500000      78.000000
75%    1022.750000  20.000000       2.0   85.750000      83.750000
max    1030.000000  21.000000       2.0   95.000000      93.000000

       english_score  programming_score  attendance_percentage  admission_year
count      30.000000          30.000000              30.000000            30.0
mean       74.166667          67.600000              84.500000          2023.0
std        10.003735          21.041175               9.379913             0.0
min        55.000000          38.000000              65.000000          2023.0
25%        67.250000          49.250000              77.250000          2023.0
50%        75.000000          66.000000              86.500000          2023.0
75%        81.750000          88.750000              91.750000          2023.0
max        90.000000          97.000000              98.000000          2023.0

In [ ]:
print(df.isnull.sum())
//if is null it will replace with the sum value

In [ ]:
display(df.head())
print(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               5
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print(df['department'].unique())
print(df['department'].value_counts())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
print(df['gender'].value_counts())

gender
Male      15
Female    15
Name: count, dtype: int64

In [ ]:
print(df['city'].unique())
print(df['city'].value_counts())

['Mumbai' 'Ahmedabad' 'Delhi' 'Hyderabad' 'Kochi' 'Pune' 'Bangalore'
 'Lucknow' 'Varanasi' 'Kolkata' 'Chennai' 'Jaipur' 'Mysore' 'Thrissur'
 'Bhopal' 'Agra' 'Patna' 'Nagpur' 'Dehradun' 'Chandigarh'
 'Thiruvananthapuram' 'Surat' 'Allahabad' 'Kanpur' 'Indore']
city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [ ]:
cs_student=df[df['department']=='Computer Science']
print(len(cs_student))
print(cs_student[['name','programming_score']])

13
              name  programming_score
0     Aarav Sharma                 91
1      Priya Patel                 79
4       Arjun Nair                 95
7      Divya Singh                 93
9       Ananya Das                 97
12      Suresh Rao                 88
14     Ajay Tiwari                 76
17  Swati Kulkarni                 92
19    Nisha Kapoor                 83
21     Tanvi Mehta                 96
24       Amit Bose                 89
26   Gaurav Shukla                 87
29  Akanksha Yadav                 94

In [ ]:
cm_students=df[(df['city']=='Chennai') | (df['city']=='Mumbai')]
print(len(cm_students))

print(cm_students[['name','city','programming_score']])

2
            name     city  programming_score
0   Aarav Sharma   Mumbai                 91
10   Vikram Iyer  Chennai                 72

In [ ]:
high=df[df['attendance_percentage']<=75]
print(high[['name','attendance_percentage']])

             name  attendance_percentage
5     Meera Joshi                     72
8    Rahul Mishra                     68
14    Ajay Tiwari                     75
16   Manoj Pandey                     65
20  Harish Pillai                     74
22   Sanjay Dubey                     70
27  Sunita Pillai                     73

In [12]:
df['Total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']
top_student=df.loc[df['Total_score'].idxmax()]
print(top_student)
low_student=df.loc[df['Total_score'].idxmin()]
print(low_student)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
Total_score                           371
Name: 9, dtype: object
student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                         56
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
Total_score                       210
Name: 16, dtype: object